# Generated by Django 5.2.7 on 2025-10-27 17:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('idpresentacion', models.AutoField(primary_key=True, serialize=False)),
                ('idmedicamento', models.IntegerField()),
                ('cantidadvalor', models.IntegerField()),
                ('cantidadunidad', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'presentacion',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contraseña', models.CharField(blank=True, max_length=255, null=True)),
                ('proveedoroauth', models.CharField(blank=True, max_length=255, null=True)),
                ('idproveedor', models.CharField(blank=True, max_length=255, null=True)),
                ('idcomuna', models.IntegerField(blank=True, null=True)),
                ('fecharegistro', models.DateField(default=datetime.date.today)),
                ('fechanacimiento', models.DateField(blank=True, null=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
